import type { NutritionPer100g } from '../types';

// Generic reference values derived from CREA (Italian National Research Institute for
// Food and Nutrition) and USDA food composition tables.  Values are per-100 g of the
// edible portion as typically consumed (cooked legumes, fresh fruit/veg, dry cereals).
// These are NOT brand-specific and are intentionally approximate averages.
// Do NOT use for medical or dietetic advice.

export type MultilingualAliases = {
  it?: string[];
  en?: string[];
  de?: string[];
  fr?: string[];
  es?: string[];
};

export type BaseIngredientNutritionEntry = {
  id:              string;
  canonicalName:   string;
  aliases:         MultilingualAliases;
  category?:       string;
  nutritionPer100g: NutritionPer100g;
};

export const BASE_INGREDIENTS_DATA: readonly BaseIngredientNutritionEntry[] = [

  // ── Cereals / carbs ───────────────────────────────────────────────────────

  {
    id:            'base-pasta-secca',
    canonicalName: 'Pasta secca',
    aliases: {
      it: ['pasta', 'pasta secca', 'spaghetti', 'penne', 'rigatoni', 'fusilli', 'tagliatelle', 'linguine', 'bucatini'],
      en: ['pasta', 'dried pasta', 'spaghetti', 'penne', 'rigatoni', 'fusilli', 'tagliatelle', 'linguine'],
      de: ['nudeln', 'pasta', 'spaghetti', 'penne', 'rigatoni', 'fusilli', 'tagliatelle'],
      fr: ['pâtes', 'pasta', 'spaghettis', 'penne', 'rigatoni', 'fusilli', 'tagliatelles'],
      es: ['pasta', 'fideos', 'espaguetis', 'penne', 'rigatoni', 'fusilli', 'pasta seca'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 350, proteinG: 12, carbsG: 70, sugarsG: 2, fatG: 1.5, fiberG: 3 },
  },
  {
    id:            'base-pasta-integrale',
    canonicalName: 'Pasta integrale',
    aliases: {
      it: ['pasta integrale', 'spaghetti integrali', 'penne integrali'],
      en: ['wholemeal pasta', 'whole wheat pasta', 'wholegrain pasta'],
      de: ['vollkornnudeln', 'vollkornpasta', 'vollkornspaghetti'],
      fr: ['pâtes complètes', 'pâtes intégrales'],
      es: ['pasta integral', 'fideos integrales'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 335, proteinG: 12, carbsG: 66, sugarsG: 1.5, fatG: 2, fiberG: 7 },
  },
  {
    id:            'base-riso-bianco',
    canonicalName: 'Riso',
    aliases: {
      it: ['riso', 'riso bianco', 'riso carnaroli', 'riso arborio'],
      en: ['rice', 'white rice', 'risotto rice', 'carnaroli rice', 'arborio rice'],
      de: ['reis', 'weißer reis', 'risottoreis'],
      fr: ['riz', 'riz blanc', 'riz pour risotto'],
      es: ['arroz', 'arroz blanco', 'arroz para risotto'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 350, proteinG: 7, carbsG: 77, sugarsG: 0, fatG: 0.5, fiberG: 1 },
  },
  {
    id:            'base-riso-basmati',
    canonicalName: 'Riso basmati',
    aliases: {
      it: ['riso basmati'],
      en: ['basmati rice'],
      de: ['basmatireis'],
      fr: ['riz basmati'],
      es: ['arroz basmati'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 348, proteinG: 7, carbsG: 77, sugarsG: 0.1, fatG: 0.5, fiberG: 0.4 },
  },
  {
    id:            'base-riso-integrale',
    canonicalName: 'Riso integrale',
    aliases: {
      it: ['riso integrale', 'riso venere'],
      en: ['brown rice', 'wholegrain rice'],
      de: ['vollkornreis', 'brauner reis'],
      fr: ['riz complet', 'riz brun'],
      es: ['arroz integral'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 335, proteinG: 7, carbsG: 70, sugarsG: 0.7, fatG: 2, fiberG: 3.5 },
  },
  {
    id:            'base-avena',
    canonicalName: 'Avena',
    aliases: {
      it: ["fiocchi d'avena", 'avena', 'fiocchi di avena', 'farina di avena', 'porridge'],
      en: ['oats', 'rolled oats', 'oat flakes', 'oatmeal', 'porridge'],
      de: ['haferflocken', 'hafer', 'haferbrei', 'porridge'],
      fr: ["flocons d'avoine", 'avoine', 'gruau', 'porridge'],
      es: ['avena', 'copos de avena', 'harina de avena', 'porridge'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 389, proteinG: 17, carbsG: 66, sugarsG: 1, fatG: 7, fiberG: 11 },
  },
  {
    id:            'base-farina-00',
    canonicalName: 'Farina 00',
    aliases: {
      it: ['farina', 'farina 00', 'farina di grano tenero', 'farina bianca', 'farina manitoba'],
      en: ['wheat flour', 'white flour', 'all-purpose flour', 'plain flour'],
      de: ['weizenmehl', 'mehl', 'weißmehl'],
      fr: ['farine de blé', 'farine blanche', 'farine de froment'],
      es: ['harina de trigo', 'harina blanca', 'harina de repostería'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 364, proteinG: 10, carbsG: 76, sugarsG: 1, fatG: 1, fiberG: 3 },
  },
  {
    id:            'base-farina-integrale',
    canonicalName: 'Farina integrale',
    aliases: {
      it: ['farina integrale', 'farina di grano duro', 'farina di farro'],
      en: ['wholemeal flour', 'whole wheat flour', 'spelt flour'],
      de: ['vollkornmehl', 'dinkelmehl'],
      fr: ['farine complète', 'farine intégrale', 'farine de blé complet'],
      es: ['harina integral', 'harina de espelta'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 339, proteinG: 13, carbsG: 68, sugarsG: 1, fatG: 2, fiberG: 10 },
  },
  {
    id:            'base-pane',
    canonicalName: 'Pane',
    aliases: {
      it: ['pane', 'pane bianco', 'pane comune', 'pane casareccio'],
      en: ['bread', 'white bread'],
      de: ['brot', 'weißbrot'],
      fr: ['pain', 'pain blanc'],
      es: ['pan', 'pan blanco'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 265, proteinG: 9, carbsG: 50, sugarsG: 3, fatG: 3, fiberG: 3 },
  },
  {
    id:            'base-pangrattato',
    canonicalName: 'Pangrattato',
    aliases: {
      it: ['pangrattato', 'pane grattugiato'],
      en: ['breadcrumbs', 'bread crumbs'],
      de: ['semmelbrösel', 'paniermehl'],
      fr: ['chapelure'],
      es: ['pan rallado'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 395, proteinG: 12, carbsG: 80, sugarsG: 3, fatG: 4, fiberG: 4 },
  },
  {
    id:            'base-cous-cous',
    canonicalName: 'Cous cous',
    aliases: {
      it: ['cous cous', 'couscous', 'cuscus'],
      en: ['couscous', 'cous cous'],
      de: ['couscous'],
      fr: ['couscous'],
      es: ['cuscús', 'couscous'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 376, proteinG: 13, carbsG: 77, sugarsG: 0.5, fatG: 0.6, fiberG: 5 },
  },
  {
    id:            'base-quinoa',
    canonicalName: 'Quinoa',
    aliases: {
      it: ['quinoa'],
      en: ['quinoa'],
      de: ['quinoa'],
      fr: ['quinoa'],
      es: ['quinoa', 'quinua'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 368, proteinG: 14, carbsG: 64, sugarsG: 1.6, fatG: 6, fiberG: 7 },
  },
  {
    id:            'base-gnocchi-patate',
    canonicalName: 'Gnocchi di patate',
    aliases: {
      it: ['gnocchi', 'gnocchi di patate', 'gnocchi di patata'],
      en: ['potato gnocchi', 'gnocchi'],
      de: ['gnocchi', 'kartoffelgnocchi'],
      fr: ['gnocchi', 'gnocchis de pomme de terre'],
      es: ['gnocchi', 'ñoquis', 'gnocchis de patata'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 153, proteinG: 3, carbsG: 33, sugarsG: 1, fatG: 1, fiberG: 1.5 },
  },
  {
    id:            'base-savoiardi',
    canonicalName: 'Savoiardi',
    aliases: {
      it: ['savoiardi', 'biscotti savoiardi'],
      en: ['ladyfinger', 'ladyfingers', 'savoiardi'],
      de: ['löffelbiskuit', 'biskuitlöffel'],
      fr: ['biscuits à la cuillère', 'boudoir'],
      es: ['bizcochos de soletilla', 'savoiardi'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 387, proteinG: 8, carbsG: 72, sugarsG: 32, fatG: 7, fiberG: 1 },
  },
  {
    id:            'base-amido-mais',
    canonicalName: 'Amido di mais',
    aliases: {
      it: ['amido di mais', 'maizena', 'amido'],
      en: ['cornstarch', 'corn starch', 'cornflour', 'maizena'],
      de: ['maisstärke', 'stärke', 'speisestärke'],
      fr: ['maïzena', 'fécule de maïs', 'amidon de maïs'],
      es: ['maicena', 'almidón de maíz', 'fécula de maíz'],
    },
    category: 'cereals',
    nutritionPer100g: { kcal: 381, proteinG: 0.3, carbsG: 91, sugarsG: 0, fatG: 0.1, fiberG: 0.9 },
  },

  // ── Dairy ─────────────────────────────────────────────────────────────────

  {
    id:            'base-latte-intero',
    canonicalName: 'Latte intero',
    aliases: {
      it: ['latte', 'latte intero', 'latte fresco', 'latte fresco intero'],
      en: ['milk', 'whole milk', 'full fat milk', 'full-fat milk'],
      de: ['milch', 'vollmilch', 'frische milch'],
      fr: ['lait', 'lait entier', 'lait frais entier'],
      es: ['leche', 'leche entera', 'leche fresca'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 61, proteinG: 3.2, carbsG: 4.8, sugarsG: 4.8, fatG: 3.3, saturatedFatG: 2.1, calciumMg: 120 },
  },
  {
    id:            'base-latte-parzialmente-scremato',
    canonicalName: 'Latte parzialmente scremato',
    aliases: {
      it: ['latte parzialmente scremato', 'latte p.s.', 'latte semi-scremato'],
      en: ['semi-skimmed milk', 'reduced fat milk', 'low fat milk'],
      de: ['halbfettmilch', 'fettarme milch', 'teilentrahmte milch'],
      fr: ['lait demi-écrémé', 'lait à faible teneur en matière grasse'],
      es: ['leche semidesnatada', 'leche semidescremada'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 46, proteinG: 3.3, carbsG: 4.8, sugarsG: 4.8, fatG: 1.6, saturatedFatG: 1.0, calciumMg: 120 },
  },
  {
    id:            'base-latte-scremato',
    canonicalName: 'Latte scremato',
    aliases: {
      it: ['latte scremato', 'latte magro'],
      en: ['skimmed milk', 'skim milk', 'fat free milk'],
      de: ['magermilch', 'entrahmte milch'],
      fr: ['lait écrémé'],
      es: ['leche desnatada', 'leche descremada'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 34, proteinG: 3.4, carbsG: 4.8, sugarsG: 4.8, fatG: 0.1, calciumMg: 123 },
  },
  {
    id:            'base-yogurt-greco',
    canonicalName: 'Yogurt greco',
    aliases: {
      it: ['yogurt greco', 'yogurt greco intero'],
      en: ['greek yogurt', 'greek yoghurt'],
      de: ['griechischer joghurt'],
      fr: ['yaourt grec', 'yogourt grec'],
      es: ['yogur griego'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 97, proteinG: 9, carbsG: 4, sugarsG: 4, fatG: 5, calciumMg: 110 },
  },
  {
    id:            'base-yogurt-bianco',
    canonicalName: 'Yogurt bianco',
    aliases: {
      it: ['yogurt', 'yogurt bianco', 'yogurt naturale', 'yogurt intero'],
      en: ['yogurt', 'yoghurt', 'plain yogurt', 'natural yogurt'],
      de: ['joghurt', 'naturjoghurt'],
      fr: ['yaourt', 'yaourt nature', 'yogourt'],
      es: ['yogur', 'yogur natural'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 61, proteinG: 4, carbsG: 4.7, sugarsG: 4.7, fatG: 3.5, calciumMg: 130 },
  },
  {
    id:            'base-burro',
    canonicalName: 'Burro',
    aliases: {
      it: ['burro', 'burro fresco', 'burro chiarificato'],
      en: ['butter', 'unsalted butter', 'clarified butter'],
      de: ['butter', 'ungesalzene butter', 'geklärte butter'],
      fr: ['beurre', 'beurre doux', 'beurre clarifié'],
      es: ['mantequilla', 'mantequilla sin sal'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 717, proteinG: 0.9, carbsG: 0.6, sugarsG: 0.6, fatG: 81, saturatedFatG: 51 },
  },
  {
    id:            'base-parmigiano',
    canonicalName: 'Parmigiano Reggiano',
    aliases: {
      it: ['parmigiano', 'parmigiano reggiano', 'grana padano', 'grana'],
      en: ['parmesan', 'parmigiano reggiano', 'grana padano'],
      de: ['parmesan', 'parmigiano reggiano'],
      fr: ['parmesan', 'parmigiano reggiano'],
      es: ['parmesano', 'queso parmesano'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 392, proteinG: 36, carbsG: 0, fatG: 26, saturatedFatG: 17, calciumMg: 1160, saltG: 1.6 },
  },
  {
    id:            'base-mozzarella',
    canonicalName: 'Mozzarella',
    aliases: {
      it: ['mozzarella', 'mozzarella di bufala', 'fior di latte'],
      en: ['mozzarella', 'buffalo mozzarella'],
      de: ['mozzarella', 'büffelmozzarella'],
      fr: ['mozzarella', 'mozzarella di bufala'],
      es: ['mozzarella', 'mozzarella de búfala'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 250, proteinG: 18, carbsG: 2.5, sugarsG: 0, fatG: 19, saturatedFatG: 12, calciumMg: 500 },
  },
  {
    id:            'base-ricotta',
    canonicalName: 'Ricotta',
    aliases: {
      it: ['ricotta', 'ricotta vaccina', 'ricotta fresca'],
      en: ['ricotta', 'ricotta cheese'],
      de: ['ricotta'],
      fr: ['ricotta'],
      es: ['ricotta'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 174, proteinG: 11, carbsG: 3, sugarsG: 3, fatG: 13, saturatedFatG: 8, calciumMg: 207 },
  },
  {
    id:            'base-mascarpone',
    canonicalName: 'Mascarpone',
    aliases: {
      it: ['mascarpone'],
      en: ['mascarpone', 'mascarpone cheese'],
      de: ['mascarpone'],
      fr: ['mascarpone'],
      es: ['mascarpone'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 430, proteinG: 5, carbsG: 3, sugarsG: 3, fatG: 44, saturatedFatG: 28 },
  },
  {
    id:            'base-panna-cucina',
    canonicalName: 'Panna da cucina',
    aliases: {
      it: ['panna', 'panna da cucina', 'panna liquida', 'panna fresca', 'panna da montare', 'panna per cucinare'],
      en: ['cream', 'cooking cream', 'heavy cream', 'whipping cream', 'double cream'],
      de: ['sahne', 'schlagsahne', 'kochsahne', 'obers'],
      fr: ['crème', 'crème fraîche', 'crème liquide', 'crème à fouetter'],
      es: ['nata', 'crema de leche', 'nata para cocinar', 'nata para montar'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 292, proteinG: 2.2, carbsG: 3.4, sugarsG: 3.4, fatG: 30, saturatedFatG: 18 },
  },
  {
    id:            'base-pecorino',
    canonicalName: 'Pecorino',
    aliases: {
      it: ['pecorino', 'pecorino romano', 'pecorino sardo', 'pecorino stagionato'],
      en: ['pecorino', 'pecorino romano'],
      de: ['pecorino'],
      fr: ['pecorino'],
      es: ['pecorino', 'queso pecorino'],
    },
    category: 'dairy',
    nutritionPer100g: { kcal: 387, proteinG: 26, carbsG: 0, fatG: 32, saturatedFatG: 21, calciumMg: 760 },
  },

  // ── Protein ───────────────────────────────────────────────────────────────

  {
    id:            'base-uova',
    canonicalName: 'Uova',
    aliases: {
      it: ['uova', 'uovo', 'uove', 'uova intere', 'tuorlo', 'tuorli', 'albume', 'albumi'],
      en: ['egg', 'eggs', 'whole egg', 'egg white', 'egg yolk'],
      de: ['ei', 'eier', 'eigelb', 'eiweiß', 'vollei'],
      fr: ['œuf', 'œufs', 'oeuf', 'oeufs', "jaune d'œuf", "blanc d'œuf"],
      es: ['huevo', 'huevos', 'yema', 'clara'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 143, proteinG: 13, carbsG: 1, fatG: 10, saturatedFatG: 3 },
  },
  {
    id:            'base-pollo',
    canonicalName: 'Pollo',
    aliases: {
      it: ['pollo', 'pollo intero', 'cosce di pollo', 'sovracosce di pollo', 'cosce o sovracosce di pollo', 'pollo arrosto'],
      en: ['chicken', 'whole chicken', 'chicken thighs', 'roast chicken', 'chicken drumsticks'],
      de: ['huhn', 'hähnchen', 'hühnchen', 'hähnchenschenkel', 'ganzes hähnchen'],
      fr: ['poulet', 'poulet entier', 'cuisses de poulet', 'poulet rôti'],
      es: ['pollo', 'pollo entero', 'muslos de pollo', 'pollo asado'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 189, proteinG: 18, carbsG: 0, fatG: 13, saturatedFatG: 3.5 },
  },
  {
    id:            'base-petto-di-pollo',
    canonicalName: 'Petto di pollo',
    aliases: {
      it: ['petto di pollo', 'petto pollo', 'filetto di pollo'],
      en: ['chicken breast', 'chicken fillet'],
      de: ['hähnchenbrust', 'hühnchenbrust', 'hähnchenfilet'],
      fr: ['blanc de poulet', 'filet de poulet', 'poitrine de poulet'],
      es: ['pechuga de pollo', 'filete de pollo'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 165, proteinG: 31, carbsG: 0, fatG: 3.6, saturatedFatG: 1 },
  },
  {
    id:            'base-manzo',
    canonicalName: 'Manzo',
    aliases: {
      it: ['manzo', 'carne di manzo', 'bistecca', 'fettine di manzo'],
      en: ['beef', 'beef steak', 'steak'],
      de: ['rindfleisch', 'rind', 'rindersteak'],
      fr: ['bœuf', 'viande de bœuf', 'steak'],
      es: ['ternera', 'carne de vacuno', 'bistec'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 250, proteinG: 26, carbsG: 0, fatG: 17, saturatedFatG: 7 },
  },
  {
    id:            'base-carne-macinata',
    canonicalName: 'Carne macinata di manzo',
    aliases: {
      it: ['carne macinata', 'carne macinata di manzo', 'macinato di manzo', 'macinato', 'trito di manzo'],
      en: ['minced beef', 'ground beef', 'beef mince'],
      de: ['hackfleisch', 'rinderhackfleisch', 'faschiertes'],
      fr: ['bœuf haché', 'viande hachée', 'haché de bœuf'],
      es: ['carne picada', 'carne molida', 'carne picada de ternera'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 235, proteinG: 17, carbsG: 0, fatG: 18, saturatedFatG: 7 },
  },
  {
    id:            'base-salmone',
    canonicalName: 'Salmone',
    aliases: {
      it: ['salmone', 'salmone fresco', 'filetto di salmone', 'salmone atlantico'],
      en: ['salmon', 'fresh salmon', 'salmon fillet', 'atlantic salmon'],
      de: ['lachs', 'frischer lachs', 'lachsfilet'],
      fr: ['saumon', 'saumon frais', 'filet de saumon'],
      es: ['salmón', 'salmón fresco', 'filete de salmón'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 208, proteinG: 20, carbsG: 0, fatG: 13, saturatedFatG: 3 },
  },
  {
    id:            'base-tonno',
    canonicalName: 'Tonno',
    aliases: {
      it: ['tonno', 'tonno al naturale', 'tonno in scatola', "tonno sott'acqua"],
      en: ['tuna', 'canned tuna', 'tuna in water'],
      de: ['thunfisch', 'thunfisch in dose', 'thunfisch in wasser'],
      fr: ['thon', 'thon en boîte', 'thon au naturel'],
      es: ['atún', 'atún en lata', 'atún al natural'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 116, proteinG: 26, carbsG: 0, fatG: 1, saturatedFatG: 0.3 },
  },
  {
    id:            'base-tofu',
    canonicalName: 'Tofu',
    aliases: {
      it: ['tofu', 'tofu naturale', 'tofu sodo'],
      en: ['tofu', 'firm tofu', 'natural tofu'],
      de: ['tofu', 'fester tofu'],
      fr: ['tofu', 'tofu ferme'],
      es: ['tofu', 'tofu firme'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 76, proteinG: 8, carbsG: 2, fatG: 4.5, fiberG: 0.3, calciumMg: 350 },
  },
  {
    id:            'base-seitan',
    canonicalName: 'Seitan',
    aliases: {
      it: ['seitan'],
      en: ['seitan', 'wheat gluten'],
      de: ['seitan'],
      fr: ['seitan'],
      es: ['seitán'],
    },
    category: 'protein',
    nutritionPer100g: { kcal: 370, proteinG: 75, carbsG: 14, fatG: 2, fiberG: 0.6 },
  },

  // ── Legumes ───────────────────────────────────────────────────────────────

  {
    id:            'base-ceci',
    canonicalName: 'Ceci',
    aliases: {
      it: ['ceci', 'ceci cotti', 'ceci in scatola'],
      en: ['chickpeas', 'chickpea', 'garbanzo beans', 'canned chickpeas'],
      de: ['kichererbsen', 'kichererbse'],
      fr: ['pois chiches', 'pois chiche'],
      es: ['garbanzos', 'garbanzo'],
    },
    category: 'legumes',
    nutritionPer100g: { kcal: 164, proteinG: 9, carbsG: 27, sugarsG: 4.8, fatG: 2.6, fiberG: 8, ironMg: 2.9 },
  },
  {
    id:            'base-lenticchie',
    canonicalName: 'Lenticchie',
    aliases: {
      it: ['lenticchie', 'lenticchie cotte', 'lenticchie rosse', 'lenticchie verdi'],
      en: ['lentils', 'red lentils', 'green lentils', 'cooked lentils'],
      de: ['linsen', 'rote linsen', 'grüne linsen'],
      fr: ['lentilles', 'lentilles rouges', 'lentilles vertes'],
      es: ['lentejas', 'lentejas rojas', 'lentejas verdes'],
    },
    category: 'legumes',
    nutritionPer100g: { kcal: 116, proteinG: 9, carbsG: 20, sugarsG: 1.8, fatG: 0.4, fiberG: 8, ironMg: 3.3 },
  },
  {
    id:            'base-fagioli',
    canonicalName: 'Fagioli',
    aliases: {
      it: ['fagioli', 'fagioli borlotti', 'fagioli cannellini', 'cannellini', 'cannellini in scatola', 'fagioli cotti', 'fagioli rossi', 'fagioli neri', 'borlotti'],
      en: ['beans', 'cannellini beans', 'kidney beans', 'red kidney beans', 'black beans', 'white beans', 'borlotti beans', 'canned beans', 'canned kidney beans'],
      de: ['bohnen', 'weiße bohnen', 'rote bohnen', 'schwarze bohnen', 'rote kidneybohnen', 'kidneybohnen', 'dosenbohnen'],
      fr: ['haricots', 'haricots blancs', 'haricots rouges', 'haricots noirs', 'haricots rouges en boîte', 'haricots kidney'],
      es: ['alubias', 'judías', 'frijoles', 'alubias rojas', 'judías negras', 'frijoles rojos', 'judías kidney'],
    },
    category: 'legumes',
    nutritionPer100g: { kcal: 127, proteinG: 8.7, carbsG: 22, sugarsG: 0.3, fatG: 0.5, fiberG: 6.5, ironMg: 2.1 },
  },
  {
    id:            'base-piselli',
    canonicalName: 'Piselli',
    aliases: {
      it: ['piselli', 'piselli freschi', 'piselli surgelati', 'piselli in scatola'],
      en: ['peas', 'garden peas', 'frozen peas', 'canned peas'],
      de: ['erbsen', 'grüne erbsen', 'tiefgekühlte erbsen'],
      fr: ['petits pois', 'pois', 'petits pois surgelés'],
      es: ['guisantes', 'arvejas', 'guisantes congelados'],
    },
    category: 'legumes',
    nutritionPer100g: { kcal: 81, proteinG: 5.4, carbsG: 14, sugarsG: 5.7, fatG: 0.4, fiberG: 5.7 },
  },

  // ── Fruit ─────────────────────────────────────────────────────────────────

  {
    id:            'base-banana',
    canonicalName: 'Banana',
    aliases: {
      it: ['banana', 'banane'],
      en: ['banana', 'bananas'],
      de: ['banane', 'bananen'],
      fr: ['banane', 'bananes'],
      es: ['plátano', 'banana', 'bananas', 'plátanos'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 89, proteinG: 1.1, carbsG: 23, sugarsG: 12, fatG: 0.3, fiberG: 2.6, potassiumMg: 358 },
  },
  {
    id:            'base-mela',
    canonicalName: 'Mela',
    aliases: {
      it: ['mela', 'mele', 'mele golden', 'mele fuji', 'mela verde'],
      en: ['apple', 'apples', 'golden apple', 'green apple'],
      de: ['apfel', 'äpfel', 'grüner apfel'],
      fr: ['pomme', 'pommes', 'pomme verte'],
      es: ['manzana', 'manzanas', 'manzana verde'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 52, proteinG: 0.3, carbsG: 14, sugarsG: 10, fatG: 0.2, fiberG: 2.4, vitaminCMg: 4.6 },
  },
  {
    id:            'base-pera',
    canonicalName: 'Pera',
    aliases: {
      it: ['pera', 'pere'],
      en: ['pear', 'pears'],
      de: ['birne', 'birnen'],
      fr: ['poire', 'poires'],
      es: ['pera', 'peras'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 57, proteinG: 0.4, carbsG: 15, sugarsG: 10, fatG: 0.1, fiberG: 3.1, vitaminCMg: 4.3 },
  },
  {
    id:            'base-fragole',
    canonicalName: 'Fragole',
    aliases: {
      it: ['fragola', 'fragole'],
      en: ['strawberry', 'strawberries'],
      de: ['erdbeere', 'erdbeeren'],
      fr: ['fraise', 'fraises'],
      es: ['fresa', 'fresas', 'frutilla'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 32, proteinG: 0.7, carbsG: 7.7, sugarsG: 4.9, fatG: 0.3, fiberG: 2, vitaminCMg: 59 },
  },
  {
    id:            'base-avocado',
    canonicalName: 'Avocado',
    aliases: {
      it: ['avocado'],
      en: ['avocado', 'avocados'],
      de: ['avocado', 'avocados'],
      fr: ['avocat', 'avocats'],
      es: ['aguacate', 'avocado', 'palta'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 160, proteinG: 2, carbsG: 9, sugarsG: 0.7, fatG: 15, saturatedFatG: 2.1, fiberG: 7, potassiumMg: 485 },
  },
  {
    id:            'base-limone',
    canonicalName: 'Limone',
    aliases: {
      it: ['limone', 'limoni', 'succo di limone', 'scorza di limone'],
      en: ['lemon', 'lemons', 'lemon juice', 'lemon zest'],
      de: ['zitrone', 'zitronen', 'zitronensaft', 'zitronenschale'],
      fr: ['citron', 'citrons', 'jus de citron', 'zeste de citron'],
      es: ['limón', 'limones', 'zumo de limón', 'ralladura de limón'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 29, proteinG: 1.1, carbsG: 9, sugarsG: 2.5, fatG: 0.3, fiberG: 2.8, vitaminCMg: 53 },
  },
  {
    id:            'base-lime',
    canonicalName: 'Lime',
    aliases: {
      it: ['lime', 'succo di lime', 'scorza di lime'],
      en: ['lime', 'limes', 'lime juice', 'lime zest'],
      de: ['limette', 'limetten', 'limettensaft'],
      fr: ['citron vert', 'lime', 'jus de citron vert'],
      es: ['lima', 'limas', 'zumo de lima'],
    },
    category: 'fruit',
    nutritionPer100g: { kcal: 30, proteinG: 0.7, carbsG: 11, sugarsG: 1.7, fatG: 0.2, fiberG: 2.8, vitaminCMg: 29 },
  },

  // ── Vegetables ────────────────────────────────────────────────────────────

  {
    id:            'base-pomodoro',
    canonicalName: 'Pomodoro',
    aliases: {
      it: ['pomodoro', 'pomodori', 'pomodorini', 'pomodori ciliegino', 'pomodori san marzano', 'pomodori pelati', 'passata di pomodoro', 'salsa di pomodoro', 'salsa pomodoro'],
      en: ['tomato', 'tomatoes', 'cherry tomatoes', 'tomato sauce', 'tomato passata', 'crushed tomatoes', 'peeled tomatoes', 'canned tomatoes', 'tinned tomatoes', 'diced tomatoes', 'chopped tomatoes', 'whole peeled tomatoes'],
      de: ['tomate', 'tomaten', 'kirschtomaten', 'tomatensoße', 'passierte tomaten', 'geschälte tomaten', 'gehackte tomaten', 'dosentomaten'],
      fr: ['tomate', 'tomates', 'tomates cerises', 'sauce tomate', 'coulis de tomate', 'tomates pelées', 'tomates concassées', 'tomates en boîte'],
      es: ['tomate', 'tomates', 'tomates cherry', 'salsa de tomate', 'tomate frito', 'tomates pelados', 'tomates troceados', 'tomate triturado'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 18, proteinG: 0.9, carbsG: 3.5, sugarsG: 2.6, fatG: 0.2, fiberG: 1.2, vitaminCMg: 19 },
  },
  {
    id:            'base-zucchina',
    canonicalName: 'Zucchina',
    aliases: {
      it: ['zucchina', 'zucchine', 'zucchino'],
      en: ['zucchini', 'courgette', 'courgettes'],
      de: ['zucchini'],
      fr: ['courgette', 'courgettes'],
      es: ['calabacín', 'calabacines', 'zucchini'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 17, proteinG: 1.2, carbsG: 3.1, sugarsG: 2.5, fatG: 0.3, fiberG: 1, vitaminCMg: 17 },
  },
  {
    id:            'base-melanzana',
    canonicalName: 'Melanzana',
    aliases: {
      it: ['melanzana', 'melanzane'],
      en: ['eggplant', 'aubergine'],
      de: ['aubergine'],
      fr: ['aubergine'],
      es: ['berenjena'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 25, proteinG: 1, carbsG: 5.9, sugarsG: 3.5, fatG: 0.2, fiberG: 3 },
  },
  {
    id:            'base-carota',
    canonicalName: 'Carote',
    aliases: {
      it: ['carota', 'carote'],
      en: ['carrot', 'carrots'],
      de: ['karotte', 'karotten', 'möhre', 'möhren'],
      fr: ['carotte', 'carottes'],
      es: ['zanahoria', 'zanahorias'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 41, proteinG: 0.9, carbsG: 9.6, sugarsG: 4.7, fatG: 0.2, fiberG: 2.8, vitaminCMg: 6 },
  },
  {
    id:            'base-cipolla',
    canonicalName: 'Cipolla',
    aliases: {
      it: ['cipolla', 'cipolle', 'cipolla rossa', 'cipolla di tropea', 'cipollotto', 'cipollotti'],
      en: ['onion', 'onions', 'red onion', 'spring onion', 'scallion'],
      de: ['zwiebel', 'zwiebeln', 'rote zwiebel', 'frühlingszwiebel'],
      fr: ['oignon', 'oignons', 'oignon rouge', 'cébette'],
      es: ['cebolla', 'cebollas', 'cebolla roja', 'cebolleta'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 40, proteinG: 1.1, carbsG: 9, sugarsG: 4.2, fatG: 0.1, fiberG: 1.7 },
  },
  {
    id:            'base-aglio',
    canonicalName: 'Aglio',
    aliases: {
      it: ['aglio', "spicchio d'aglio", "spicchi d'aglio", 'spicchio aglio', 'aglio in polvere', 'aglio secco'],
      en: ['garlic', 'garlic clove', 'garlic cloves', 'garlic powder'],
      de: ['knoblauch', 'knoblauchzehe', 'knoblauchpulver'],
      fr: ['ail', 'gousse d\'ail', 'gousses d\'ail', 'ail en poudre'],
      es: ['ajo', 'diente de ajo', 'dientes de ajo', 'ajo en polvo'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 149, proteinG: 6.4, carbsG: 33, sugarsG: 1, fatG: 0.5, fiberG: 2.1 },
  },
  {
    id:            'base-spinaci',
    canonicalName: 'Spinaci',
    aliases: {
      it: ['spinaci', 'spinacino', 'spinaci freschi'],
      en: ['spinach', 'baby spinach', 'fresh spinach'],
      de: ['spinat', 'babyspinat', 'frischer spinat'],
      fr: ['épinard', 'épinards', 'jeunes épinards'],
      es: ['espinaca', 'espinacas', 'espinacas frescas'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 23, proteinG: 2.9, carbsG: 3.6, sugarsG: 0.4, fatG: 0.4, fiberG: 2.2, ironMg: 2.7, calciumMg: 99 },
  },
  {
    id:            'base-patata',
    canonicalName: 'Patate',
    aliases: {
      it: ['patata', 'patate'],
      en: ['potato', 'potatoes'],
      de: ['kartoffel', 'kartoffeln'],
      fr: ['pomme de terre', 'pommes de terre'],
      es: ['patata', 'patatas', 'papa', 'papas'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 77, proteinG: 2, carbsG: 17, sugarsG: 0.8, fatG: 0.1, fiberG: 2.2, potassiumMg: 421 },
  },
  {
    id:            'base-patata-dolce',
    canonicalName: 'Patata dolce',
    aliases: {
      it: ['patata dolce', 'patate dolci'],
      en: ['sweet potato', 'sweet potatoes', 'yam'],
      de: ['süßkartoffel', 'süßkartoffeln', 'batate'],
      fr: ['patate douce', 'patates douces'],
      es: ['boniato', 'batata', 'patata dulce', 'camote'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 86, proteinG: 1.6, carbsG: 20, sugarsG: 4.2, fatG: 0.1, fiberG: 3, vitaminCMg: 2.4 },
  },
  {
    id:            'base-funghi',
    canonicalName: 'Funghi',
    aliases: {
      it: ['funghi', 'funghi champignon', 'funghi porcini', 'funghi misti', 'champignon'],
      en: ['mushrooms', 'mushroom', 'champignon', 'porcini mushrooms'],
      de: ['pilze', 'champignons', 'steinpilze'],
      fr: ['champignons', 'champignon', 'cèpes'],
      es: ['champiñones', 'setas', 'hongos'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 22, proteinG: 3.1, carbsG: 3.3, sugarsG: 2, fatG: 0.3, fiberG: 1 },
  },
  {
    id:            'base-mais',
    canonicalName: 'Mais dolce',
    aliases: {
      it: ['mais', 'mais dolce', 'granoturco', 'granturco', 'mais in scatola', 'mais surgelato'],
      en: ['corn', 'sweet corn', 'sweetcorn', 'corn on the cob', 'canned corn'],
      de: ['mais', 'zuckermais', 'maiskolben', 'mais aus der dose'],
      fr: ['maïs', 'maïs doux', 'maïs en boîte', 'épi de maïs'],
      es: ['maíz', 'choclo', 'elote', 'maíz dulce', 'maíz en lata'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 86, proteinG: 3.2, carbsG: 19, sugarsG: 3.2, fatG: 1.2, fiberG: 2.7 },
  },
  {
    id:            'base-peperone',
    canonicalName: 'Peperone rosso',
    aliases: {
      it: ['peperone', 'peperoni', 'peperone rosso', 'peperoni rossi', 'peperone giallo', 'peperoni gialli', 'peperone verde', 'capsicum'],
      en: ['bell pepper', 'bell peppers', 'red pepper', 'red bell pepper', 'green bell pepper', 'yellow bell pepper', 'green pepper', 'yellow pepper', 'capsicum'],
      de: ['paprika', 'rote paprika', 'grüne paprika', 'gelbe paprika', 'paprikaschote'],
      fr: ['poivron', 'poivron rouge', 'poivron vert', 'poivron jaune'],
      es: ['pimiento', 'pimiento rojo', 'pimiento verde', 'pimiento amarillo'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 31, proteinG: 1, carbsG: 6, sugarsG: 4.2, fatG: 0.3, fiberG: 2.1, vitaminCMg: 127 },
  },
  {
    id:            'base-zucca',
    canonicalName: 'Zucca',
    aliases: {
      it: ['zucca', 'zucca butternut', 'zucca gialla', 'zucca delica', 'zucca mantovana'],
      en: ['pumpkin', 'butternut squash', 'squash'],
      de: ['kürbis', 'butternut-kürbis', 'hokkaido-kürbis'],
      fr: ['citrouille', 'potiron', 'courge butternut'],
      es: ['calabaza', 'calabaza butternut', 'zapallo'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 26, proteinG: 1, carbsG: 6.5, sugarsG: 2.8, fatG: 0.1, fiberG: 0.5, vitaminCMg: 9 },
  },
  {
    id:            'base-fagiolini',
    canonicalName: 'Fagiolini',
    aliases: {
      it: ['fagiolini', 'fagiolino', 'fagiolini verdi', 'cornetti'],
      en: ['green beans', 'string beans', 'french beans'],
      de: ['grüne bohnen', 'prinzessbohnen'],
      fr: ['haricots verts'],
      es: ['judías verdes', 'ejotes', 'vainitas'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 31, proteinG: 1.8, carbsG: 7, sugarsG: 3.3, fatG: 0.2, fiberG: 3.4, vitaminCMg: 12 },
  },
  {
    id:            'base-sedano',
    canonicalName: 'Sedano',
    aliases: {
      it: ['sedano', 'sedano bianco', 'costa sedano', 'coste sedano', 'gambo di sedano'],
      en: ['celery', 'celery stalk'],
      de: ['sellerie', 'stangensellerie'],
      fr: ['céleri', 'branche de céleri'],
      es: ['apio', 'tallo de apio'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 16, proteinG: 0.7, carbsG: 3.5, sugarsG: 1.8, fatG: 0.2, fiberG: 1.6, vitaminCMg: 3 },
  },
  {
    id:            'base-scalogno',
    canonicalName: 'Scalogno',
    aliases: {
      it: ['scalogno', 'scalogni'],
      en: ['shallot', 'shallots'],
      de: ['schalotte', 'schalotten'],
      fr: ['échalote', 'échalotes'],
      es: ['chalota', 'chalotas'],
    },
    category: 'vegetables',
    nutritionPer100g: { kcal: 72, proteinG: 2.5, carbsG: 17, sugarsG: 7.9, fatG: 0.1, fiberG: 3.2 },
  },

  // ── Fats / condiments ─────────────────────────────────────────────────────

  {
    id:            'base-olio-evo',
    canonicalName: 'Olio extravergine di oliva',
    aliases: {
      it: ['olio', "olio d'oliva", 'olio di oliva', 'olio extravergine', 'olio extravergine di oliva', 'olio evo'],
      en: ['olive oil', 'extra virgin olive oil', 'evoo'],
      de: ['olivenöl', 'natives olivenöl extra'],
      fr: ["huile d'olive", "huile d'olive vierge extra"],
      es: ['aceite de oliva', 'aceite de oliva virgen extra', 'aove'],
    },
    category: 'fats',
    nutritionPer100g: { kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, saturatedFatG: 14 },
  },
  {
    id:            'base-zucchero',
    canonicalName: 'Zucchero',
    aliases: {
      it: ['zucchero', 'zucchero semolato', 'zucchero bianco', 'zucchero a velo', 'zucchero di canna'],
      en: ['sugar', 'white sugar', 'caster sugar', 'icing sugar', 'cane sugar'],
      de: ['zucker', 'weißer zucker', 'puderzucker', 'rohrzucker'],
      fr: ['sucre', 'sucre blanc', 'sucre glace', 'sucre de canne'],
      es: ['azúcar', 'azúcar blanco', 'azúcar glass', 'azúcar moreno'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 392, proteinG: 0, carbsG: 100, sugarsG: 100, fatG: 0 },
  },
  {
    id:            'base-miele',
    canonicalName: 'Miele',
    aliases: {
      it: ['miele', 'miele di acacia', 'miele millefiori'],
      en: ['honey', 'acacia honey'],
      de: ['honig', 'akazienhonig'],
      fr: ['miel', "miel d'acacia"],
      es: ['miel', 'miel de acacia'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 304, proteinG: 0.3, carbsG: 82, sugarsG: 82, fatG: 0, fiberG: 0.2 },
  },
  {
    id:            'base-sale',
    canonicalName: 'Sale',
    aliases: {
      it: ['sale', 'sale fino', 'sale grosso', 'sale marino', 'sale integrale'],
      en: ['salt', 'sea salt', 'table salt', 'kosher salt'],
      de: ['salz', 'meersalz', 'tafelsalz'],
      fr: ['sel', 'sel de mer', 'fleur de sel'],
      es: ['sal', 'sal marina', 'sal de mesa'],
    },
    category: 'condiments',
    nutritionPer100g: { saltG: 100, sodiumMg: 39300 },
  },
  {
    id:            'base-pepe',
    canonicalName: 'Pepe',
    aliases: {
      it: ['pepe', 'pepe nero', 'pepe bianco', 'pepe macinato'],
      en: ['pepper', 'black pepper', 'white pepper', 'ground pepper'],
      de: ['pfeffer', 'schwarzer pfeffer', 'weißer pfeffer'],
      fr: ['poivre', 'poivre noir', 'poivre blanc'],
      es: ['pimienta', 'pimienta negra', 'pimienta blanca'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 251, proteinG: 11, carbsG: 64, fatG: 3.3, fiberG: 26 },
  },
  {
    id:            'base-cannella',
    canonicalName: 'Cannella',
    aliases: {
      it: ['cannella', 'cannella in polvere', 'stecca di cannella'],
      en: ['cinnamon', 'ground cinnamon', 'cinnamon stick'],
      de: ['zimt', 'zimtpulver', 'zimtstange'],
      fr: ['cannelle', 'cannelle en poudre', 'bâton de cannelle'],
      es: ['canela', 'canela en polvo', 'rama de canela'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 247, proteinG: 4, carbsG: 81, sugarsG: 2.2, fatG: 1.2, fiberG: 53 },
  },
  {
    id:            'base-basilico',
    canonicalName: 'Basilico',
    aliases: {
      it: ['basilico', 'basilico fresco', 'foglie di basilico'],
      en: ['basil', 'fresh basil', 'basil leaves'],
      de: ['basilikum', 'frisches basilikum'],
      fr: ['basilic', 'basilic frais', 'feuilles de basilic'],
      es: ['albahaca', 'albahaca fresca'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 23, proteinG: 3.2, carbsG: 2.7, fatG: 0.6, fiberG: 1.6, vitaminCMg: 18 },
  },
  {
    id:            'base-prezzemolo',
    canonicalName: 'Prezzemolo',
    aliases: {
      it: ['prezzemolo', 'prezzemolo fresco', 'foglie di prezzemolo'],
      en: ['parsley', 'fresh parsley', 'flat-leaf parsley', 'curly parsley'],
      de: ['petersilie', 'frische petersilie', 'glatte petersilie'],
      fr: ['persil', 'persil frais', 'persil plat'],
      es: ['perejil', 'perejil fresco', 'perejil liso'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 36, proteinG: 3, carbsG: 6.3, fatG: 0.8, fiberG: 3.3, vitaminCMg: 133 },
  },
  {
    id:            'base-origano',
    canonicalName: 'Origano',
    aliases: {
      it: ['origano', 'origano secco', 'origano essiccato'],
      en: ['oregano', 'dried oregano'],
      de: ['oregano', 'getrockneter oregano'],
      fr: ['origan', 'origan séché'],
      es: ['orégano', 'orégano seco'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 265, proteinG: 9, carbsG: 69, fatG: 4.3, fiberG: 43 },
  },
  {
    id:            'base-paprika',
    canonicalName: 'Paprika',
    aliases: {
      it: ['paprika', 'paprica', 'paprika dolce', 'paprika affumicata', 'paprika piccante'],
      en: ['paprika', 'sweet paprika', 'smoked paprika', 'hot paprika'],
      de: ['paprikapulver', 'süßes paprikapulver', 'geräuchertes paprikapulver'],
      fr: ['paprika', 'paprika doux', 'paprika fumé'],
      es: ['pimentón', 'paprika', 'pimentón dulce', 'pimentón ahumado'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 282, proteinG: 14, carbsG: 54, fatG: 13, fiberG: 35 },
  },
  {
    id:            'base-cumino',
    canonicalName: 'Cumino',
    aliases: {
      it: ['cumino', 'cumino in polvere', 'semi di cumino'],
      en: ['cumin', 'ground cumin', 'cumin seeds'],
      de: ['kreuzkümmel', 'kumin', 'kümmel'],
      fr: ['cumin', 'cumin en poudre', 'graines de cumin'],
      es: ['comino', 'comino molido', 'semillas de comino'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 375, proteinG: 18, carbsG: 44, fatG: 22, fiberG: 11 },
  },
  {
    id:            'base-cacao',
    canonicalName: 'Cacao amaro',
    aliases: {
      it: ['cacao', 'cacao amaro', 'cacao in polvere', 'cacao amaro in polvere'],
      en: ['cocoa', 'cocoa powder', 'unsweetened cocoa'],
      de: ['kakao', 'kakaopulver', 'ungesüßter kakao'],
      fr: ['cacao', 'poudre de cacao', 'cacao en poudre'],
      es: ['cacao', 'cacao en polvo', 'cacao puro'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 228, proteinG: 20, carbsG: 58, fatG: 14, fiberG: 37 },
  },
  {
    id:            'base-brodo',
    canonicalName: 'Brodo',
    aliases: {
      it: ['brodo', 'brodo di pollo', 'brodo di verdure', 'brodo di carne', 'brodo vegetale', 'brodo di manzo'],
      en: ['broth', 'stock', 'chicken broth', 'vegetable broth', 'beef broth', 'chicken stock'],
      de: ['brühe', 'hühnerbrühe', 'gemüsebrühe', 'rinderbrühe'],
      fr: ['bouillon', 'bouillon de poulet', 'bouillon de légumes', 'bouillon de bœuf'],
      es: ['caldo', 'caldo de pollo', 'caldo de verduras', 'caldo de carne'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 5, proteinG: 0.5, carbsG: 0.5, fatG: 0.1 },
  },
  {
    id:            'base-coriandolo',
    canonicalName: 'Coriandolo',
    aliases: {
      it: ['coriandolo', 'coriandolo fresco', 'foglie di coriandolo'],
      en: ['cilantro', 'coriander', 'fresh coriander', 'coriander leaves'],
      de: ['koriander', 'frischer koriander', 'korianderblätter'],
      fr: ['coriandre', 'coriandre fraîche', 'feuilles de coriandre'],
      es: ['cilantro', 'coriandro', 'cilantro fresco'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 23, proteinG: 2.1, carbsG: 3.7, fatG: 0.5, fiberG: 2.8, vitaminCMg: 27 },
  },
  {
    id:            'base-rosmarino',
    canonicalName: 'Rosmarino',
    aliases: {
      it: ['rosmarino', 'rosmarino fresco', 'rosmarino essiccato'],
      en: ['rosemary', 'fresh rosemary', 'dried rosemary'],
      de: ['rosmarin', 'frischer rosmarin'],
      fr: ['romarin', 'romarin frais'],
      es: ['romero', 'romero fresco'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 131, proteinG: 3.3, carbsG: 21, fatG: 5.9, fiberG: 14 },
  },
  {
    id:            'base-noce-moscata',
    canonicalName: 'Noce moscata',
    aliases: {
      it: ['noce moscata', 'noce moscata grattugiata', 'noce moscata in polvere'],
      en: ['nutmeg', 'ground nutmeg'],
      de: ['muskatnuss', 'muskat'],
      fr: ['noix de muscade', 'muscade'],
      es: ['nuez moscada'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 525, proteinG: 6, carbsG: 49, fatG: 36, fiberG: 21 },
  },
  {
    id:            'base-vino-bianco',
    canonicalName: 'Vino bianco',
    aliases: {
      it: ['vino bianco', 'vino bianco secco', 'vino da cucina bianco'],
      en: ['white wine', 'dry white wine', 'cooking white wine'],
      de: ['weißwein', 'trockener weißwein'],
      fr: ['vin blanc', 'vin blanc sec'],
      es: ['vino blanco', 'vino blanco seco'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 68, proteinG: 0.1, carbsG: 0.6, fatG: 0 },
  },
  {
    id:            'base-vino-rosso',
    canonicalName: 'Vino rosso',
    aliases: {
      it: ['vino rosso', 'vino rosso secco', 'vino da cucina rosso'],
      en: ['red wine', 'dry red wine', 'cooking red wine'],
      de: ['rotwein', 'trockener rotwein'],
      fr: ['vin rouge', 'vin rouge sec'],
      es: ['vino tinto', 'vino tinto seco'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 68, proteinG: 0.1, carbsG: 2.6, fatG: 0 },
  },
  {
    id:            'base-zafferano',
    canonicalName: 'Zafferano',
    aliases: {
      it: ['zafferano', 'bustina zafferano', 'zafferano in polvere'],
      en: ['saffron', 'saffron threads', 'saffron powder'],
      de: ['safran', 'safranfäden'],
      fr: ['safran', 'pistils de safran'],
      es: ['azafrán', 'hebras de azafrán'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 310, proteinG: 11, carbsG: 65, fatG: 6, fiberG: 4 },
  },
  {
    id:            'base-alloro',
    canonicalName: 'Alloro',
    aliases: {
      it: ['alloro', 'foglia alloro', 'foglie di alloro', 'alloro secco', 'lauro'],
      en: ['bay leaf', 'bay leaves', 'laurel'],
      de: ['lorbeer', 'lorbeerblatt', 'lorbeerblätter'],
      fr: ['laurier', 'feuille de laurier', 'feuilles de laurier'],
      es: ['laurel', 'hoja de laurel', 'hojas de laurel'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 313, proteinG: 7.6, carbsG: 75, fatG: 8.4, fiberG: 26 },
  },
  {
    id:            'base-caffe',
    canonicalName: 'Caffè',
    aliases: {
      it: ['caffè', 'caffe', 'caffè forte', 'caffè espresso', 'caffè ristretto', 'caffè freddo'],
      en: ['coffee', 'espresso', 'strong coffee', 'cold coffee'],
      de: ['kaffee', 'espresso', 'starker kaffee'],
      fr: ['café', 'expresso', 'café fort'],
      es: ['café', 'espresso', 'café fuerte'],
    },
    category: 'condiments',
    nutritionPer100g: { kcal: 2, proteinG: 0.3, carbsG: 0, fatG: 0 },
  },

  // ── Nuts / seeds ──────────────────────────────────────────────────────────

  {
    id:            'base-mandorle',
    canonicalName: 'Mandorle',
    aliases: {
      it: ['mandorle', 'mandorla', 'mandorle pelate', 'mandorle tostate'],
      en: ['almonds', 'almond', 'blanched almonds', 'roasted almonds'],
      de: ['mandeln', 'mandelkerne', 'geröstete mandeln'],
      fr: ['amandes', 'amande', 'amandes grillées'],
      es: ['almendras', 'almendra', 'almendras tostadas'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 579, proteinG: 21, carbsG: 22, sugarsG: 4.4, fatG: 50, saturatedFatG: 3.8, fiberG: 12.5, calciumMg: 264 },
  },
  {
    id:            'base-noci',
    canonicalName: 'Noci',
    aliases: {
      it: ['noci', 'noce', 'noci comuni', 'gherigli di noce'],
      en: ['walnuts', 'walnut', 'walnut halves'],
      de: ['walnüsse', 'walnuss', 'walnusskerne'],
      fr: ['noix', 'cerneaux de noix'],
      es: ['nueces', 'nuez'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 654, proteinG: 15, carbsG: 14, sugarsG: 2.6, fatG: 65, saturatedFatG: 6, fiberG: 6.7 },
  },
  {
    id:            'base-semi-chia',
    canonicalName: 'Semi di chia',
    aliases: {
      it: ['semi di chia', 'chia'],
      en: ['chia seeds', 'chia'],
      de: ['chiasamen', 'chia'],
      fr: ['graines de chia', 'chia'],
      es: ['semillas de chía', 'chía'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 486, proteinG: 17, carbsG: 42, sugarsG: 0, fatG: 31, saturatedFatG: 3.3, fiberG: 34, calciumMg: 631 },
  },
  {
    id:            'base-semi-sesamo',
    canonicalName: 'Semi di sesamo',
    aliases: {
      it: ['semi di sesamo', 'sesamo', 'sesamo tostato'],
      en: ['sesame seeds', 'sesame', 'toasted sesame'],
      de: ['sesamsamen', 'sesam', 'gerösteter sesam'],
      fr: ['graines de sésame', 'sésame', 'sésame grillé'],
      es: ['semillas de sésamo', 'sésamo', 'ajonjolí'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 573, proteinG: 17, carbsG: 23, sugarsG: 0.3, fatG: 50, saturatedFatG: 7, fiberG: 11.8, calciumMg: 975 },
  },
  {
    id:            'base-pinoli',
    canonicalName: 'Pinoli',
    aliases: {
      it: ['pinoli', 'pinolo'],
      en: ['pine nuts', 'pine kernels', 'pignoli'],
      de: ['pinienkerne', 'pinoli'],
      fr: ['pignons de pin', 'pignons'],
      es: ['piñones', 'piñón'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 673, proteinG: 14, carbsG: 13, sugarsG: 3.6, fatG: 68, saturatedFatG: 4.9, fiberG: 3.7 },
  },
  {
    id:            'base-tahini',
    canonicalName: 'Tahini',
    aliases: {
      it: ['tahini', 'tahina', 'pasta di sesamo', 'crema di sesamo'],
      en: ['tahini', 'tahina', 'sesame paste'],
      de: ['tahini', 'sesammus', 'sesampaste'],
      fr: ['tahini', 'tahina', 'crème de sésame'],
      es: ['tahini', 'tahina', 'pasta de sésamo'],
    },
    category: 'nuts',
    nutritionPer100g: { kcal: 595, proteinG: 17, carbsG: 21, sugarsG: 0.5, fatG: 54, saturatedFatG: 7.6, fiberG: 9 },
  },
];
